spring.application.name: training-diary-2

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: MANUEL
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: masterisiatfm@gmail.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true